language: node_js
node_js:
- stable
cache: false
before_install:
  - npm install -g codeclimate-test-reporter
  - psql -c 'drop database if exists test;' -U postgres
  - psql -c 'create database test;' -U postgres
services:
  - postgresql
script:
  - npm test
after_success:
  - npm run coveralls
addons:
  postgresql: "9.3"
